# Generated by Django 4.1.4 on 2022-12-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipdeclientes',
            table='ip_address',
        ),
    ]
